version: '3'
services:
  postgres:
    container_name: PostgreSql
    image: postgres
    restart: always
    environment:
      TZ: Asia/Shanghai
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: postgres
    ports:
      - '5432:5432'